//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod
    {
        public int prod_id { get; set; }
        public string cust_email { get; set; }
        public int item { get; set; }
        public string prod_name { get; set; }
        public int price { get; set; }
    
        public virtual Cust Cust { get; set; }
    }
}
